import type { Metadata } from 'next'
import {ThemeProvider} from 'next-themes';

import { Footer, Navbar } from '@/components';
import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <ThemeProvider attribute="class">
        <Navbar />
        <body className="dark:bg-nft-dark bg-wjite min-h-screen">{children}</body>
        <Footer />
      </ThemeProvider>
    </html>
  )
}
