import type { Metadata } from "next";
import Script from "next/script";

import Providers from "./providers";
import { Footer, Navbar } from "@/components";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="dark:bg-nft-dark bg-white min-h-screen">
        <Providers>
          <Navbar />
          <main className="pt-65">{children}</main>
          <Footer />

          <Script
            src="https://kit.fontawesome.com/f248074af6.js"
            crossOrigin="anonymous"
            rel="preload"
            type="module"
          />
        </Providers>
      </body>
    </html>
  );
}
